; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Virtual Pool"
!define PRODUCT_VERSION "3.3"
!define PRODUCT_PUBLISHER "儒安科技"
!define PRODUCT_WEB_SITE "http://www.greenorbs.com"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\putty.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\release\installVB.bat"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\Virtual Pool"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite try
  File "..\..\build\VirtualBox-4.3.26-98988-Win.exe"
  File "..\..\build\putty.exe"
  SetOutPath "$INSTDIR\release\iconengines"
  File "..\..\build\release\iconengines\qsvgicon.dll"
  SetOutPath "$INSTDIR\release"
  File "..\..\build\release\icudt53.dll"
  File "..\..\build\release\icuin53.dll"
  File "..\..\build\release\icuuc53.dll"
  SetOutPath "$INSTDIR\release\imageformats"
  File "..\..\build\release\imageformats\qdds.dll"
  File "..\..\build\release\imageformats\qgif.dll"
  File "..\..\build\release\imageformats\qicns.dll"
  File "..\..\build\release\imageformats\qico.dll"
  File "..\..\build\release\imageformats\qjp2.dll"
  File "..\..\build\release\imageformats\qjpeg.dll"
  File "..\..\build\release\imageformats\qmng.dll"
  File "..\..\build\release\imageformats\qsvg.dll"
  File "..\..\build\release\imageformats\qtga.dll"
  File "..\..\build\release\imageformats\qtiff.dll"
  File "..\..\build\release\imageformats\qwbmp.dll"
  File "..\..\build\release\imageformats\qwebp.dll"
  SetOutPath "$INSTDIR\release"
  File "..\..\build\release\libgcc_s_dw2-1.dll"
  File "..\..\build\release\libstdc++-6.dll"
  File "..\..\build\release\libwinpthread-1.dll"
  SetOutPath "$INSTDIR\release\platforms"
  File "..\..\build\release\platforms\qwindows.dll"
  SetOutPath "$INSTDIR\release"
  File "..\..\build\release\Qt5Core.dll"
  File "..\..\build\release\Qt5Gui.dll"
  File "..\..\build\release\Qt5Svg.dll"
  File "..\..\build\release\Qt5Widgets.dll"
  File "..\..\build\release\qt_ca.qm"
  File "..\..\build\release\qt_cs.qm"
  File "..\..\build\release\qt_de.qm"
  File "..\..\build\release\qt_fi.qm"
  File "..\..\build\release\qt_hu.qm"
  File "..\..\build\release\qt_it.qm"
  File "..\..\build\release\qt_ja.qm"
  File "..\..\build\release\qt_ru.qm"
  File "..\..\build\release\qt_sk.qm"
  File "..\..\build\release\qt_uk.qm"
  File "..\..\build\release\VirtualPool.exe"
  File "..\..\build\installVB.bat"
  CreateDirectory "$SMPROGRAMS\Virtual Pool"
  CreateShortCut "$SMPROGRAMS\Virtual Pool\Virtual Pool.lnk" "$INSTDIR\release\VirtualPool.exe"
  CreateShortCut "$DESKTOP\Virtual Pool.lnk" "$INSTDIR\release\VirtualPool.exe"
  SetOutPath "$INSTDIR"
  File "..\..\build\ubuntu-14.04.1-desktop-i386.iso"
  File "..\..\build\ui_mainwindow.h"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\Virtual Pool\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\Virtual Pool\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\VirtualPool.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\VirtualPool.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\VirtualBox-4.3.26-98988-Win.exe"
  Delete "$INSTDIR\ui_mainwindow.h"
  Delete "$INSTDIR\ubuntu-14.04.1-desktop-i386.iso"
  Delete "$INSTDIR\release\VirtualPool.exe"
  Delete "$INSTDIR\release\qt_uk.qm"
  Delete "$INSTDIR\release\qt_sk.qm"
  Delete "$INSTDIR\release\qt_ru.qm"
  Delete "$INSTDIR\release\qt_ja.qm"
  Delete "$INSTDIR\release\qt_it.qm"
  Delete "$INSTDIR\release\qt_hu.qm"
  Delete "$INSTDIR\release\qt_fi.qm"
  Delete "$INSTDIR\release\qt_de.qm"
  Delete "$INSTDIR\release\qt_cs.qm"
  Delete "$INSTDIR\release\qt_ca.qm"
  Delete "$INSTDIR\release\Qt5Widgets.dll"
  Delete "$INSTDIR\release\Qt5Svg.dll"
  Delete "$INSTDIR\release\Qt5Gui.dll"
  Delete "$INSTDIR\release\Qt5Core.dll"
  Delete "$INSTDIR\release\platforms\qwindows.dll"
  Delete "$INSTDIR\release\libwinpthread-1.dll"
  Delete "$INSTDIR\release\libstdc++-6.dll"
  Delete "$INSTDIR\release\libgcc_s_dw2-1.dll"
  Delete "$INSTDIR\release\imageformats\qwebp.dll"
  Delete "$INSTDIR\release\imageformats\qwbmp.dll"
  Delete "$INSTDIR\release\imageformats\qtiff.dll"
  Delete "$INSTDIR\release\imageformats\qtga.dll"
  Delete "$INSTDIR\release\imageformats\qsvg.dll"
  Delete "$INSTDIR\release\imageformats\qmng.dll"
  Delete "$INSTDIR\release\imageformats\qjpeg.dll"
  Delete "$INSTDIR\release\imageformats\qjp2.dll"
  Delete "$INSTDIR\release\imageformats\qico.dll"
  Delete "$INSTDIR\release\imageformats\qicns.dll"
  Delete "$INSTDIR\release\imageformats\qgif.dll"
  Delete "$INSTDIR\release\imageformats\qdds.dll"
  Delete "$INSTDIR\release\icuuc53.dll"
  Delete "$INSTDIR\release\icuin53.dll"
  Delete "$INSTDIR\release\icudt53.dll"
  Delete "$INSTDIR\release\iconengines\qsvgicon.dll"
  Delete "$INSTDIR\putty.exe"

  Delete "$SMPROGRAMS\Virtual Pool\Uninstall.lnk"
  Delete "$SMPROGRAMS\Virtual Pool\Website.lnk"
  Delete "$DESKTOP\Virtual Pool.lnk"
  Delete "$SMPROGRAMS\Virtual Pool\Virtual Pool.lnk"

  RMDir "$SMPROGRAMS\Virtual Pool"
  RMDir "$INSTDIR\release\platforms"
  RMDir "$INSTDIR\release\imageformats"
  RMDir "$INSTDIR\release\iconengines"
  RMDir "$INSTDIR\release"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd